"""Corpus manifest contract — issue #91 phase 2.

The :class:`CorpusManifest` records the *expected* shape of a corpus
generated by :func:`tests.fixtures.generate_corpus.generate_corpus`. It
is the **contract** that integration tests assert against: every count
is hard-coded at design time and the generator is responsible for
producing exactly that many files of each kind. Tests read these
constants and check ``len(scanner.results) == manifest.total_files``
etc, which means a regression in either the generator or the scanner
will surface immediately.

The dataclass is frozen so a manifest cannot be mutated mid-test.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Mapping


# Hardcoded design-time constants. The generator MUST produce a corpus
# that matches these exactly when invoked with the default seed (42).
# Changing any of these is a contract change and breaks integration
# tests on purpose.

#: Total files in the corpus.
TOTAL_FILES = 10_000

#: Number of duplicate groups (each with 2-5 members, all > 1 MB so they
#: exceed the 1 MB dedup threshold the analyzer enforces).
EXPECTED_DUPLICATE_GROUPS = 47

#: Total files that participate in any duplicate group. This is the
#: *count of dupe-bearing rows*, not "extra copies" — i.e. all members
#: of all 47 groups summed.
EXPECTED_DUPLICATE_FILES = 121

#: Per-pattern PII fixture counts. Maps the pattern name from
#: :data:`src.compliance.pii_engine.PiiEngine.DEFAULT_PATTERNS` to the
#: number of *files* containing at least one hit. NB: a single file may
#: contain more than one hit; this counts files, not raw matches.
EXPECTED_PII_FINDINGS: Mapping[str, int] = {
    "email": 4,
    "iban_tr": 3,
    "phone_tr": 2,
    "tckn": 2,
    "credit_card": 1,
}

#: Naming-violation files (MIT R1/R2/R3/R4 style + Windows-reserved
#: lookalikes). Counted by the generator and asserted as-is.
EXPECTED_NAMING_VIOLATIONS = 50

#: Files with mtime > 365 days ago.
EXPECTED_STALE_1YEAR = 1_500
#: Files with mtime > 1095 days ago. Subset of stale_1year.
EXPECTED_STALE_3YEAR = 500
#: Files with mtime > 180 days ago. Superset of stale_1year.
EXPECTED_STALE_180 = 2_500

#: Files with size > 100 MB. (matches the analyzer ``large_files``
#: insight threshold).
EXPECTED_LARGE_FILES = 200
#: Files with size > 1 GB. (analyzer ``very_large`` threshold).
EXPECTED_VERY_LARGE = 50

#: Files matching the temp-file pattern: extensions
#: ``.tmp`` ``.temp`` ``.bak`` ``.old`` ``.cache`` ``.log`` plus
#: ``~$Document.docx`` lookalikes.
EXPECTED_TEMP_FILES = 40

#: Empty (zero-byte) files.
EXPECTED_EMPTY_FILES = 8

#: Hidden / system files (Linux: leading dot in name).
EXPECTED_HIDDEN_FILES = 30


@dataclass(frozen=True)
class CorpusManifest:
    """Frozen contract describing a generated corpus.

    Two manifests with the same ``out_dir`` + ``seed`` are guaranteed
    by the generator to refer to byte-identical file trees. All other
    fields are hard-coded design-time invariants — see the module-level
    constants for the rationale on each one.
    """

    out_dir: Path
    seed: int = 42
    total_files: int = TOTAL_FILES

    expected_duplicates: int = EXPECTED_DUPLICATE_GROUPS
    expected_duplicate_files: int = EXPECTED_DUPLICATE_FILES

    expected_pii_findings: Mapping[str, int] = field(
        default_factory=lambda: dict(EXPECTED_PII_FINDINGS)
    )

    expected_naming_violations: int = EXPECTED_NAMING_VIOLATIONS
    expected_empty_files: int = EXPECTED_EMPTY_FILES
    expected_temp_files: int = EXPECTED_TEMP_FILES
    expected_hidden_files: int = EXPECTED_HIDDEN_FILES

    expected_stale_1year: int = EXPECTED_STALE_1YEAR
    expected_stale_3year: int = EXPECTED_STALE_3YEAR
    expected_stale_180: int = EXPECTED_STALE_180

    expected_large_files: int = EXPECTED_LARGE_FILES
    expected_very_large: int = EXPECTED_VERY_LARGE

    def to_dict(self) -> dict:
        """Serialise to a JSON-safe dict (Path → str)."""
        d = asdict(self)
        d["out_dir"] = str(self.out_dir)
        # asdict() copies the dict; ensure pii_findings is a plain dict.
        d["expected_pii_findings"] = dict(self.expected_pii_findings)
        return d

    def to_json(self) -> str:
        return json.dumps(self.to_dict(), indent=2, sort_keys=True)

    def write_json(self, path: Path) -> None:
        path.write_text(self.to_json(), encoding="utf-8")
